n1 = int(input("Digite um valor: "))
n2 = int(input("Digite outro valor: "))
print(f"A soma vale {n1 + n2}")
print(f"A multiplicação vale {n1 * n2}")
print(f"A divisão vale {n1 / n2:.3f}")
print(f"A divisão inteira vale {n1 // n2}")
print(f"O resto da divisão vale {n1 % n2}")